# Generated by Django 3.2.12 on 2025-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_statistics', '0002_auto_20210208_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstatistics',
            name='london_fields_overs',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='London Fields Overs Bowled'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='london_fields_wickets',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='London Fields Wickets Taken'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='opposition_overs',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True, verbose_name='Opposition overs Bowled'),
        ),
        migrations.AlterField(
            model_name='matchstatistics',
            name='opposition_wickets',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Opposition Wickets Taken'),
        ),
    ]
