# Generated by Django 3.2 on 2026-07-24 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batsman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batsman',
            name='how_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batsman.wickettype'),
        ),
        migrations.AlterField(
            model_name='batsman',
            name='runs',
            field=models.PositiveIntegerField(verbose_name='Runs'),
        ),
    ]
