# Generated by Django 6.0.7 on 2026-07-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batsman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batsman',
            name='how_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='batsman.wickettype'),
        ),
        migrations.AlterField(
            model_name='batsman',
            name='runs',
            field=models.PositiveIntegerField(verbose_name='Runs'),
        ),
    ]
